version: '3.8'
services:
  summit-freighters:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: summit-freighters-container
    ports:
      - "8181:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - summit-freighters-network

networks:
  summit-freighters-network:
    driver: bridge
